# Reference: http://www.sogo-unyu.co.jp/useful/track/

wheel_radius: 0.555
wheel_width: 0.600
trailer_width: 8.610
trailer_depth: 2.480
trailer_height: 0.655
hitch_length: 0.165
tractor_width: 5.400
tractor_depth: 2.480
tractor_height: 2.235
