simple_semitrailer_navigation:
  ros__parameters:
    control_rate: 10

    prediction_horizon: 40
    sampling_period: 0.5
    damping_coefficient: 100.
    difference_spacing: 1.e-4
    state_weight: [0.5, 0.5, 0.5, 0.5]
    input_weight: [0.5, 0.5]
    dummy_weight: 0.01
    max_coupler_angle: 1.57079632679
    max_longitudinal_velocity: 10.
    max_steering_angle: 0.785398163397
